apiVersion: v1
kind: Service
metadata:
  name: skin-disease-detector-service
spec:
  type: NodePort        # Bisa diakses dari luar cluster
  selector:
    app: skin-disease-detector    # Arahkan ke pod berlabel ini
  ports:
  - protocol: TCP
    port: 80            # Port yang diexpose ke luar
    targetPort: 5000    # Port di dalam container
    nodePort: 30080     # Port di node Minikube (akses via browser)